export const DATE_START_FILTER = 'DATE_START_FILTER';

export const FETCH_LAUNCHES_START = 'FETCH_LAUNCHES_START';
export const FETCH_LAUNCHES_SUCCESS = 'FETCH_LAUNCHES_SUCCESS';
export const FETCH_LAUNCHES_FAILURE = 'FETCH_LAUNCHES_FAILURE';
